language: c
dist: binoic
addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-findlib
    - ffmpeg
    - libao-dev
    - portaudio19-dev
    - libasound2-dev
    - libpulse-dev
    - libgstreamer1.0-dev
    - libgstreamer-plugins-base1.0-dev
    - libsrt-dev
    - libmad0-dev
    - libtag1-dev
    - libmp3lame-dev
    - libshine-dev
    - libogg-dev
    - libvorbis-dev
    - libspeex-dev
    - libtheora-dev
    - libopus-dev
    - libfdk-aac-dev
    - libfaad-dev
    - libflac-dev
    - ladspa-sdk
    - liblilv-dev
    - libsoundtouch-dev
    - libsamplerate-dev
    - libgavl-dev
    - libavutil-dev
    - libavformat-dev
    - libavcodec-dev
    - libswscale-dev
    - libavdevice-dev
    - frei0r-plugins-dev
    - dssi-dev
    - liblo-dev

script:
  - cp PACKAGES.default PACKAGES
  - ./bootstrap
  - ./configure
  - make
  - make -C liquidsoap test
