language: c
dist: binoic
sudo: false
addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-findlib
    - ffmpeg
    - libmp3lame-dev

script:
  - cp PACKAGES.minimal PACKAGES
  - ./bootstrap
  - ./configure
  - make
  - make -C liquidsoap test