language: c
dist: bionic
addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-findlib
    - ffmpeg
    - libao-dev
    - portaudio19-dev
    - libasound2-dev
    - libpulse-dev
    - libgstreamer1.0-dev
    - libgstreamer-plugins-base1.0-dev
    - libmad0-dev
    - libtag1-dev
    - libmp3lame-dev
    - libshine-dev
    - libogg-dev
    - libvorbis-dev
    - libspeex-dev
    - libtheora-dev
    - libopus-dev
    - libfdk-aac-dev
    - libfaad-dev
    - libflac-dev
    - ladspa-sdk
    - liblilv-dev
    - libsoundtouch-dev
    - libsamplerate-dev
    - libgavl-dev
    - libavutil-dev
    - libavformat-dev
    - libavcodec-dev
    - libswscale-dev
    - libavdevice-dev
    - frei0r-plugins-dev
    - dssi-dev
    - liblo-dev
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev
    - libmagic-dev
    - libssl-dev
    - pandoc

# tsdl: does not build with this version of SDL2
before_install:
  - export OPAMYES=1
  - curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh -o /tmp/install.sh
  - echo /usr/local/bin | sh /tmp/install.sh
  - opam init --disable-sandboxing --compiler=4.08.0
  - opam update
  - opam install pcre xmlm sedlex menhir camomile magic yojson camlimages inotify ssl
  - eval `opam config env`

# srt: library not recent enough in travis
script:
  - export OPAMYES=1
  - opam pin add ocaml-shine
  - opam pin add ocaml-lilv
  - cat PACKAGES.default | grep -v ocaml-srt > PACKAGES
  - ./bootstrap
  - ./configure
  - make
  - make -C liquidsoap test
