language: c
dist: bionic
addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-findlib
    - ffmpeg
    - libao-dev
    - portaudio19-dev
    - libasound2-dev
    - libpulse-dev
    - libgstreamer1.0-dev
    - libgstreamer-plugins-base1.0-dev
    - libmad0-dev
    - libtag1-dev
    - libmp3lame-dev
    - libshine-dev
    - libogg-dev
    - libvorbis-dev
    - libspeex-dev
    - libtheora-dev
    - libopus-dev
    - libfdk-aac-dev
    - libfaad-dev
    - libflac-dev
    - ladspa-sdk
    - liblilv-dev
    - libsoundtouch-dev
    - libsamplerate-dev
    - libgavl-dev
    - libavutil-dev
    - libavformat-dev
    - libavcodec-dev
    - libswscale-dev
    - libavdevice-dev
    - frei0r-plugins-dev
    - dssi-dev
    - liblo-dev

before_install:
  - export OPAMYES=1
  - sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
  - opam init
  - opam switch create 4.08.0
  - opam install xmlm
  - eval `opam config env`

# srt: library not recent enough in travis
# shine: we don't have dune
# lilv: we don't have dune
script:
  - cat PACKAGES.default | grep -v ocaml-srt | grep -v ocaml-shine | grep -v ocaml-lilv > PACKAGES
  - ./bootstrap
  - ./configure
  - make
  - make -C liquidsoap test
